
default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: yarn_store_development

test:
  <<: *default
  database: yarn_store_test

production:
  <<: *default
  database: yarn_store_production
  username: yarn_store
  password: <%= ENV['YARN_STORE_DATABASE_PASSWORD'] %>
